### ISSUE TITLE
crash on Chat using

### ISSUE THREAD

**Issue by Alexey-T** [veksha/cuda_codeium#5]
```
Python 3.8.10
Loaded session: "history session.json", 0ms, 0 file(s)
Startup: 300ms, plugins: 0ms ()
Init: cuda_codeium
Init: cudatext
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_codeium/__init__.py", line 380, in Ask
    self.request_GetChatMessage(question)
  File "/home/user/.config/cudatext/py/cuda_codeium/__init__.py", line 393, in request_GetChatMessage
    from . import proto_pb2
  File "/home/user/.config/cudatext/py/cuda_codeium/proto_pb2.py", line 5, in <module>
    from google.protobuf.internal import builder as _builder
ImportError: cannot import name 'builder' from 'google.protobuf.internal' (/usr/lib/python3/dist-packages/google/protobuf/internal/__init__.py)
ERROR: Exception in CudaText for Ask: ImportError: cannot import name 'builder' from 'google.protobuf.internal' (/usr/lib/python3/dist-packages/google/protobuf/internal/__init__.py)
```

- got new token
- called the chat
- entered 'what year is now?'

**Comment by Alexey-T** [comment]
fix is:

```
        sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
        from . import proto_pb2
```

**Comment by veksha** [comment]
fixed. is it working on your system now?

**Comment by Alexey-T** [comment]
Yes, ok
